//
//  ISOCodeData.swift
//  CurrencyConverter
//
//  Created by Anthony Jerez on 11/12/23.
//

import Foundation

class Currency: Equatable {
    var code: String
    var country: String
    var flag: String

    init(code: String, country: String, flag: String) {
        self.code = code
        self.country = country
        self.flag = flag
    }
    
    static func == (lhs: Currency, rhs: Currency) -> Bool {
        return lhs.code == rhs.code && lhs.country == rhs.country && lhs.flag == rhs.flag
    }
}
// 161 Currency Codes Supported By Exchange Rates API
let Currencies: [Currency] = [
    Currency(code: "AED", country: "United Arab Emirates", flag: "🇦🇪"),
    Currency(code: "AFN", country: "Afghanistan", flag: "🇦🇫"),
    Currency(code: "ALL", country: "Albania", flag: "🇦🇱"),
    Currency(code: "AMD", country: "Armenia", flag: "🇦🇲"),
    Currency(code: "ANG", country: "Netherlands Antilles", flag: "🇧🇶"),
    Currency(code: "AOA", country: "Angola", flag: "🇦🇴"),
    Currency(code: "ARS", country: "Argentina", flag: "🇦🇷"),
    Currency(code: "AUD", country: "Australia", flag: "🇦🇺"),
    Currency(code: "AWG", country: "Aruba", flag: "🇦🇼"),
    Currency(code: "AZN", country: "Azerbaijan", flag: "🇦🇿"),
    Currency(code: "BAM", country: "Bosnia and Herzegovina", flag: "🇧🇦"),
    Currency(code: "BBD", country: "Barbados", flag: "🇧🇧"),
    Currency(code: "BDT", country: "Bangladesh", flag: "🇧🇩"),
    Currency(code: "BGN", country: "Bulgaria", flag: "🇧🇬"),
    Currency(code: "BHD", country: "Bahrain", flag: "🇧🇭"),
    Currency(code: "BIF", country: "Burundi", flag: "🇧🇮"),
    Currency(code: "BMD", country: "Bermuda", flag: "🇧🇲"),
    Currency(code: "BND", country: "Brunei", flag: "🇧🇳"),
    Currency(code: "BOB", country: "Bolivia", flag: "🇧🇴"),
    Currency(code: "BRL", country: "Brazil", flag: "🇧🇷"),
    Currency(code: "BSD", country: "Bahamas", flag: "🇧🇸"),
    Currency(code: "BTN", country: "Bhutan", flag: "🇧🇹"),
    Currency(code: "BWP", country: "Botswana", flag: "🇧🇼"),
    Currency(code: "BYN", country: "Belarus", flag: "🇧🇾"),
    Currency(code: "BZD", country: "Belize", flag: "🇧🇿"),
    Currency(code: "CAD", country: "Canada", flag: "🇨🇦"),
    Currency(code: "CDF", country: "Democratic Republic of the Congo", flag: "🇨🇩"),
    Currency(code: "CHF", country: "Switzerland", flag: "🇨🇭"),
    Currency(code: "CLP", country: "Chile", flag: "🇨🇱"),
    Currency(code: "CNY", country: "China", flag: "🇨🇳"),
    Currency(code: "COP", country: "Colombia", flag: "🇨🇴"),
    Currency(code: "CRC", country: "Costa Rica", flag: "🇨🇷"),
    Currency(code: "CUP", country: "Cuba", flag: "🇨🇺"),
    Currency(code: "CVE", country: "Cape Verde", flag: "🇨🇻"),
    Currency(code: "CZK", country: "Czech Republic", flag: "🇨🇿"),
    Currency(code: "DJF", country: "Djibouti", flag: "🇩🇯"),
    Currency(code: "DKK", country: "Denmark", flag: "🇩🇰"),
    Currency(code: "DOP", country: "Dominican Republic", flag: "🇩🇴"),
    Currency(code: "DZD", country: "Algeria", flag: "🇩🇿"),
    Currency(code: "EGP", country: "Egypt", flag: "🇪🇬"),
    Currency(code: "ERN", country: "Eritrea", flag: "🇪🇷"),
    Currency(code: "ETB", country: "Ethiopia", flag: "🇪🇹"),
    Currency(code: "EUR", country: "European Union", flag: "🇪🇺"),
    Currency(code: "FJD", country: "Fiji", flag: "🇫🇯"),
    Currency(code: "FKP", country: "Falkland Islands", flag: "🇫🇰"),
    Currency(code: "FOK", country: "Faroe Islands", flag: "🇫🇴"),
    Currency(code: "GBP", country: "United Kingdom", flag: "🇬🇧"),
    Currency(code: "GEL", country: "Georgia", flag: "🇬🇪"),
    Currency(code: "GGP", country: "Guernsey", flag: "🇬🇬"),
    Currency(code: "GHS", country: "Ghana", flag: "🇬🇭"),
    Currency(code: "GIP", country: "Gibraltar", flag: "🇬🇮"),
    Currency(code: "GMD", country: "The Gambia", flag: "🇬🇲"),
    Currency(code: "GNF", country: "Guinea", flag: "🇬🇳"),
    Currency(code: "GTQ", country: "Guatemala", flag: "🇬🇹"),
    Currency(code: "GYD", country: "Guyana", flag: "🇬🇾"),
    Currency(code: "HKD", country: "Hong Kong", flag: "🇭🇰"),
    Currency(code: "HNL", country: "Honduras", flag: "🇭🇳"),
    Currency(code: "HRK", country: "Croatia", flag: "🇭🇷"),
    Currency(code: "HTG", country: "Haiti", flag: "🇭🇹"),
    Currency(code: "HUF", country: "Hungary", flag: "🇭🇺"),
    Currency(code: "IDR", country: "Indonesia", flag: "🇮🇩"),
    Currency(code: "ILS", country: "Israel", flag: "🇮🇱"),
    Currency(code: "IMP", country: "Isle of Man", flag: "🇮🇲"),
    Currency(code: "INR", country: "India", flag: "🇮🇳"),
    Currency(code: "IQD", country: "Iraq", flag: "🇮🇶"),
    Currency(code: "IRR", country: "Iran", flag: "🇮🇷"),
    Currency(code: "ISK", country: "Iceland", flag: "🇮🇸"),
    Currency(code: "JEP", country: "Jersey", flag: "🇯🇪"),
    Currency(code: "JMD", country: "Jamaica", flag: "🇯🇲"),
    Currency(code: "JOD", country: "Jordan", flag: "🇯🇴"),
    Currency(code: "JPY", country: "Japan", flag: "🇯🇵"),
    Currency(code: "KES", country: "Kenya", flag: "🇰🇪"),
    Currency(code: "KGS", country: "Kyrgyzstan", flag: "🇰🇬"),
    Currency(code: "KHR", country: "Cambodia", flag: "🇰🇭"),
    Currency(code: "KID", country: "Kiribati", flag: "🇰🇮"),
    Currency(code: "KMF", country: "Comoros", flag: "🇰🇲"),
    Currency(code: "KRW", country: "South Korea", flag: "🇰🇷"),
    Currency(code: "KWD", country: "Kuwait", flag: "🇰🇼"),
    Currency(code: "KYD", country: "Cayman Islands", flag: "🇰🇾"),
    Currency(code: "KZT", country: "Kazakhstan", flag: "🇰🇿"),
    Currency(code: "LAK", country: "Laos", flag: "🇱🇦"),
    Currency(code: "LBP", country: "Lebanon", flag: "🇱🇧"),
    Currency(code: "LKR", country: "Sri Lanka", flag: "🇱🇰"),
    Currency(code: "LRD", country: "Liberia", flag: "🇱🇷"),
    Currency(code: "LSL", country: "Lesotho", flag: "🇱🇸"),
    Currency(code: "LYD", country: "Libya", flag: "🇱🇾"),
    Currency(code: "MAD", country: "Morocco", flag: "🇲🇦"),
    Currency(code: "MDL", country: "Moldova", flag: "🇲🇩"),
    Currency(code: "MGA", country: "Madagascar", flag: "🇲🇬"),
    Currency(code: "MKD", country: "North Macedonia", flag: "🇲🇰"),
    Currency(code: "MMK", country: "Myanmar", flag: "🇲🇲"),
    Currency(code: "MNT", country: "Mongolia", flag: "🇲🇳"),
    Currency(code: "MOP", country: "Macau", flag: "🇲🇴"),
    Currency(code: "MRU", country: "Mauritania", flag: "🇲🇷"),
    Currency(code: "MUR", country: "Mauritius", flag: "🇲🇺"),
    Currency(code: "MVR", country: "Maldives", flag: "🇲🇻"),
    Currency(code: "MWK", country: "Malawi", flag: "🇲🇼"),
    Currency(code: "MXN", country: "Mexico", flag: "🇲🇽"),
    Currency(code: "MYR", country: "Malaysia", flag: "🇲🇾"),
    Currency(code: "MZN", country: "Mozambique", flag: "🇲🇿"),
    Currency(code: "NAD", country: "Namibia", flag: "🇳🇦"),
    Currency(code: "NGN", country: "Nigeria", flag: "🇳🇬"),
    Currency(code: "NIO", country: "Nicaragua", flag: "🇳🇮"),
    Currency(code: "NOK", country: "Norway", flag: "🇳🇴"),
    Currency(code: "NPR", country: "Nepal", flag: "🇳🇵"),
    Currency(code: "NZD", country: "New Zealand", flag: "🇳🇿"),
    Currency(code: "OMR", country: "Oman", flag: "🇴🇲"),
    Currency(code: "PAB", country: "Panama", flag: "🇵🇦"),
    Currency(code: "PEN", country: "Peru", flag: "🇵🇪"),
    Currency(code: "PGK", country: "Papua New Guinea", flag: "🇵🇬"),
    Currency(code: "PHP", country: "Philippines", flag: "🇵🇭"),
    Currency(code: "PKR", country: "Pakistan", flag: "🇵🇰"),
    Currency(code: "PLN", country: "Poland", flag: "🇵🇱"),
    Currency(code: "PYG", country: "Paraguay", flag: "🇵🇾"),
    Currency(code: "QAR", country: "Qatar", flag: "🇶🇦"),
    Currency(code: "RON", country: "Romania", flag: "🇷🇴"),
    Currency(code: "RSD", country: "Serbia", flag: "🇷🇸"),
    Currency(code: "RUB", country: "Russia", flag: "🇷🇺"),
    Currency(code: "RWF", country: "Rwanda", flag: "🇷🇼"),
    Currency(code: "SAR", country: "Saudi Arabia", flag: "🇸🇦"),
    Currency(code: "SBD", country: "Solomon Islands", flag: "🇸🇧"),
    Currency(code: "SCR", country: "Seychelles", flag: "🇸🇨"),
    Currency(code: "SDG", country: "Sudan", flag: "🇸🇩"),
    Currency(code: "SEK", country: "Sweden", flag: "🇸🇪"),
    Currency(code: "SGD", country: "Singapore", flag: "🇸🇬"),
    Currency(code: "SHP", country: "Saint Helena", flag: "🇸🇭"),
    Currency(code: "SLE", country: "Sierra Leone", flag: "🇸🇱"),
    Currency(code: "SOS", country: "Somalia", flag: "🇸🇴"),
    Currency(code: "SRD", country: "Suriname", flag: "🇸🇷"),
    Currency(code: "SSP", country: "South Sudan", flag: "🇸🇸"),
    Currency(code: "STN", country: "São Tomé and Príncipe", flag: "🇸🇹"),
    Currency(code: "SYP", country: "Syria", flag: "🇸🇾"),
    Currency(code: "SZL", country: "Eswatini", flag: "🇸🇿"),
    Currency(code: "THB", country: "Thailand", flag: "🇹🇭"),
    Currency(code: "TJS", country: "Tajikistan", flag: "🇹🇯"),
    Currency(code: "TMT", country: "Turkmenistan", flag: "🇹🇲"),
    Currency(code: "TND", country: "Tunisia", flag: "🇹🇳"),
    Currency(code: "TOP", country: "Tonga", flag: "🇹🇴"),
    Currency(code: "TRY", country: "Turkey", flag: "🇹🇷"),
    Currency(code: "TTD", country: "Trinidad and Tobago", flag: "🇹🇹"),
    Currency(code: "TVD", country: "Tuvalu", flag: "🇹🇻"),
    Currency(code: "TWD", country: "Taiwan", flag: "🇹🇼"),
    Currency(code: "TZS", country: "Tanzania", flag: "🇹🇿"),
    Currency(code: "UAH", country: "Ukraine", flag: "🇺🇦"),
    Currency(code: "UGX", country: "Uganda", flag: "🇺🇬"),
    Currency(code: "USD", country: "United States", flag: "🇺🇸"),
    Currency(code: "UYU", country: "Uruguay", flag: "🇺🇾"),
    Currency(code: "UZS", country: "Uzbekistan", flag: "🇺🇿"),
    Currency(code: "VES", country: "Venezuela", flag: "🇻🇪"),
    Currency(code: "VND", country: "Vietnam", flag: "🇻🇳"),
    Currency(code: "VUV", country: "Vanuatu", flag: "🇻🇺"),
    Currency(code: "WST", country: "Samoa", flag: "🇼🇸"),
    Currency(code: "XAF", country: "CEMAC", flag: "🇨🇫"),
    Currency(code: "XCD", country: "Org of Eastern Caribbean States", flag: "🇧🇶"),
    Currency(code: "XDR", country: "International Monetary Fund", flag: "🌐"),
    Currency(code: "XOF", country: "CFA", flag: "🇧🇯"),
    Currency(code: "XPF", country: "Collectivités d'Outre-Mer", flag: "🇵🇫"),
    Currency(code: "YER", country: "Yemen", flag: "🇾🇪"),
    Currency(code: "ZAR", country: "South Africa", flag: "🇿🇦"),
    Currency(code: "ZMW", country: "Zambia", flag: "🇿🇲"),
    Currency(code: "ZWL", country: "Zimbabwe", flag: "🇿🇼")
]

func getCurrencies() -> [Currency] {
    return Currencies
}
